services:
  redis:
    image: redis:7-alpine
    container_name: lighthouse-redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: .
    container_name: lighthouse-api
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
      - WORKER_CONCURRENCY=1
      - API_KEY=wKuU92vSNq67J16/GF55q1s5SYgztBy5vqQ9lILuM+I=
    depends_on:
      redis:
        condition: service_healthy