name: Simple CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Upgrade npm to latest
        run: npm install -g npm@latest

      - name: Install backend dependencies
        run: npm ci

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Build application
        run: npm run build

      - name: ✅ Build successful
        run: echo "Build completed successfully!"